name: Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential g++ make
    
    - name: Check compiler version
      run: make check-compiler
    
    - name: Setup project structure
      run: make quick-setup
    
    - name: Check project structure
      run: make check-structure
    
    - name: Build project (default)
      run: make all
    
    - name: Build debug version
      run: make debug
    
    - name: Build release version
      run: make release
    
    - name: Run tests (no input)
      run: make run-no-input
    
    - name: Run with sample input
      run: make run
    
    - name: Static analysis (if cppcheck available)
      run: |
        sudo apt-get install -y cppcheck
        make analyze
      continue-on-error: true

    - name: Upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-outputs
        path: |
          bin/**
          build/**
        if-no-files-found: ignore
